### ISSUE TITLE
[PT][BUG] Opção always_online das Settings não está sendo obedecida

### ISSUE THREAD

**Issue by edisoncm-ti** [EvolutionAPI/evolution-api#324]
#### Descrição:
Utilizo a Evolution-API para fazer autoatedimento através do N8N e Typebot e na minha opinião, um bot deve estar online 24/7, para dar a impressão ao lead de que tem alguém do outro lado respondendo.

Ocorre que nos testes realizados na Evolution-API v1.6.1, mesmo setando como true o parâmetro always_online, a instância só aparece como online se for aberta no dispositivo móvel.

#### Passos para Reproduzir:
1. Criar ou alterar as Settings de uma instância, informando o parâmetro always_online como true.
2. Executar o findSettings para confirmar que a opção foi realmente gravada.
3. Consultar nos logs VERBOSE, para se certificar de que realmente o parâmetro foi gravado e está ativo.

#### Comportamento Esperado:
Ao definir o parâmetro always_online como true, na barra de status do WhatsApp deveria aparecer sempre como Online, mesmo que o dispositivo móvel estivesse bloqueado ou até mesmo, desligado.

#### Comportamento Atual:
Só está aparecendo como Online na barra de status do WhatsApp, caso o usuário acesse pelo dispositivo móvel.

#### Capturas de Tela/Vídeos:
![c4451b20-999a-4c84-b143-b7f52893a5c5](https://github.com/EvolutionAPI/evolution-api/assets/135462452/fc06c522-c359-4760-9142-8a5fc54c7cbd)

Neste exemplo, o bot responde normalmente e faz a leitura imediata da mensagem, o que é o comportamento esperado, porém, o status de Online não aparece, sendo apresentado o "Visto por último" de quando acessei pelo dispositivo móvel pela última vez.

#### Ambiente:
- **Servidor:** Docket/Debian 11
- **Versão da API:** v1.6.1
- **Outras Especificações de Hardware/Software:** 4 vCPU / 8 GB RAM

#### Envio de Logs:
Caso seja necessário, basta solicitar e enviarei por Whatsapp no privado.

#### Notas Adicionais:
Não é uma correção emergencial, mas devido a minha forma de uso quase que exclusivamente para autoatendimento, seria significativamente importante.

Desde já agradeço!

Edison Martins

**Comment by diluh** [comment]
@edisoncm-ti  
Estou enfrentando o mesmo problema pórem ao inverso, quando eu desmarco a opção o sistema ainda mantem o usuario sempre online.  E acaba afetando as notificações porque o SOM de notificação não chega no celular.

Você conseguiu corrigir isso?

**Comment by cafi** [comment]
> @edisoncm-ti Estou enfrentando o mesmo problema pórem ao inverso, quando eu desmarco a opção o sistema ainda mantem o usuario sempre online. E acaba afetando as notificações porque o SOM de notificação não chega no celular.
> 
> Você conseguiu corrigir isso?

Conseguiu resolver??

**Comment by nektariosfarah** [comment]
Hello team,

I am experiencing the exact same issue on the latest Docker image. Even when alwaysOnline and readMessages are strictly set to false, the WhatsApp linked device remains constantly in the "Active" state.

The core problem this causes:
Because the device never switches to "Last active..." and stays "Active" infinitely, WhatsApp servers assume I am actively looking at WhatsApp Web. As a result, all incoming push notifications on my physical mobile phone are muted/silenced (No sound).

Steps to reproduce:

Create a new instance with alwaysOnline: false.
Link the device via QR code.
Completely close the Evolution Manager UI (to ensure no active WebSockets are keeping the presence alive).
Restart the container (docker compose restart evolution-api).
Wait for more than 5 minutes (to trigger the setInterval in whatsapp.baileys.service.ts).
Expected behavior: The linked device status on the phone should change to "Last active today at...".
Actual behavior: The status remains stuck on "Active" forever, and phone notifications remain muted.

It seems the this.setPresence({ presence: 'unavailable' }); is either not firing or is being overridden by another process in the latest Baileys engine.

Fixing this is critical for users who rely on their physical phones alongside the API. Looking forward to a patch. Thank you!
