### ISSUE TITLE
Não consigo aceitar convite para grupos

### ISSUE THREAD

**Issue by odraude7** [EvolutionAPI/evolution-api#694]
### Welcome!

- [x] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou com problema com a função de aceitar convite para grupo. 

Estou utilizando a rota:
{{baseUrl}}/group/acceptInviteCode/{{instance}}?inviteCode={{inviteCode}}

E estou passando o inviteCode que recebo no groupInviteMessage.

Mas é retornado error

### What did you expect?

Que seja possível aceitar convites para grupos

### What did you observe instead of what you expected?

Porém Ao enviar a requisição vi me retorna o seguinte erro:

```
400 - "{\"status\":400,\"error\":\"Bad Request\",\"response\":{\"message\":[{\"property\":\"inviteCode\",\"message\":\"inviteCode does not match pattern \\\"^[a-zA-Z0-9]{22}$\\\"\"}]}}"
```

Já testei várias vezes e o inviteCode que eu recebo sempre tem 16 caracteres e não é apenas alfanumérico. Ou seja, realmente não passa no pattern, mas é o que está chegando pra mim.

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.

**Comment by johnnybs2** [comment]
Estou com o mesmo problema.

**Comment by KauaMB2** [comment]
## Solution/Solução

### ENGLISH:
The REGEX specified in the API return says that only an alphanumeric string of exactly 22 characters is accepted. Therefore, if the invite link is `https://chat.whatsapp.com/L3aExanF53C2zIpFzU6B73`, instead of putting the entire link, put the last 22 characters (`L3aExanF53C2zIpFzU6B73`). It worked on my `v1.8.1`.

### PORTUGUÊS:
A REGEX especificada no retorno da API diz que somente é aceito uma string alfanumérica de exatamente 22 caracteres. Sendo assim, se o link de convite é `https://chat.whatsapp.com/L3aExanF53C2zIpFzU6B73`, ao invés de colocar o link inteiro, coloque os últimos 22 caracteres(`L3aExanF53C2zIpFzU6B73`). Funcionou na minha `v1.8.1`.
